[package]
name = "types"
version = "0.1.0"
authors = ["GuilhermeVBeira <guilherme.vieira.beira@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
